#' Run multiple TACT grafting replicates
#'
#' Runs [run_tact_grafting()] repeatedly using sequential random seeds and
#' replicate-specific output prefixes. The function writes a tab-delimited
#' manifest linking each replicate and seed to its principal tree and validation
#' files.
#'
#' Replicate output prefixes are generated by appending `_rep001`, `_rep002`,
#' and so forth to `out_prefix`.
#'
#' @param n_replicates Integer. Number of TACT grafting replicates to run.
#' @param seed_start Integer. Seed used for the first replicate. Subsequent
#'   replicates use consecutive integer seeds generated with [base::seq.int()].
#' @param out_prefix Character. Common output prefix. A replicate identifier is
#'   appended automatically to this prefix for each call to
#'   [run_tact_grafting()]. The manifest is written using the unmodified common
#'   prefix.
#' @param ... Additional arguments passed to [run_tact_grafting()]. Do not pass
#'   `seed` or `out_prefix` through `...`, because this function supplies those
#'   arguments separately for each replicate.
#'
#' @return An object of class `tact_grafting_replicates`, represented as a list
#'   with three elements:
#'   \describe{
#'     \item{results}{A list containing the result returned by each call to
#'       [run_tact_grafting()].}
#'     \item{manifest}{A data frame recording replicate numbers, seeds, and
#'       principal output paths.}
#'     \item{manifest_file}{The path to the tab-delimited replicate manifest.}
#'   }
#'
#' @details
#' Replicate seeds are generated as consecutive integers beginning with
#' `seed_start`. The manifest is written to
#' `<out_prefix>_replicate_manifest.tsv` and includes paths to the cleaned tree,
#' realm-labelled trees, validation reports, taxonomy mismatch reports, and raw
#' TACT output for each replicate.
#'
#' The stochastic result of each run depends on the seed and on the arguments
#' supplied to [run_tact_grafting()]. For stronger wrapper-level randomization,
#' use `nonmono_allocation = "random"`.
#'
#' @examples
#' \dontrun{
#' res <- run_tact_grafting_replicates(
#'   n_replicates = 10,
#'   seed_start = 1,
#'   out_prefix = "project/results/tact/Formicidae_complete",
#'   backbone_tree = "project/results/grafted/final_tree.tre",
#'   taxonomy = "project/tables/antwiki-valid-species.txt",
#'   taxonomy_format = "antwiki",
#'   tact_runner = "docker",
#'   docker_image = "jonchang/tact",
#'   nonmono = "split",
#'   nonmono_allocation = "random",
#'   biogeo = TRUE,
#'   country_realm_map = "project/tables/country_udvardy_realm.tsv",
#'   write_biogeo_labelled_trees = FALSE,
#'   keep_temp = FALSE
#' )
#'
#' res$manifest
#' res$manifest_file
#' }
#'
#' @export
run_tact_grafting_replicates <- function(
    n_replicates,
    seed_start = 1,
    out_prefix,
    ...
) {
  seeds <- seq.int(seed_start, length.out = n_replicates)
  out <- vector("list", n_replicates)

  for (i in seq_len(n_replicates)) {
    rep_prefix <- sprintf("%s_rep%03d", out_prefix, i)

    message(
      "\n===== TACT replicate ",
      i,
      " / ",
      n_replicates,
      " | seed = ",
      seeds[i],
      " =====\n"
    )

    out[[i]] <- run_tact_grafting(
      out_prefix = rep_prefix,
      seed = seeds[i],
      ...
    )
  }

  manifest <- do.call(
    rbind,
    lapply(seq_along(out), function(i) {
      paths <- out[[i]]$paths

      data.frame(
        replicate = i,
        seed = seeds[i],
        cleaned_tree = paths$cleaned_tree,
        cleaned_tree_biogeo_labels = paths$cleaned_tree_biogeo_labels,
        backbone_biogeo_labels = paths$backbone_biogeo_labels,
        validation = paths$validation,
        taxonomy_mismatch_summary = paths$taxonomy_mismatch_summary,
        tree_not_taxonomy = paths$tree_not_taxonomy,
        taxonomy_not_tree = paths$taxonomy_not_tree,
        raw_tact_output_tree = paths$raw_tact_output_tree,
        stringsAsFactors = FALSE
      )
    })
  )

  manifest_file <- paste0(out_prefix, "_replicate_manifest.tsv")

  utils::write.table(
    manifest,
    manifest_file,
    sep = "\t",
    row.names = FALSE,
    quote = FALSE
  )

  structure(
    list(
      results = out,
      manifest = manifest,
      manifest_file = manifest_file
    ),
    class = "tact_grafting_replicates"
  )
}
